# Memoria para Gradle (Minecraft necesita bastante)
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# ===== Versiones de Minecraft y Forge =====
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

# ===== Datos del mod Panthrixs Galaxy =====
mod_id=panthrixsgalaxy
mod_name=Panthrixs Galaxy
mod_license=All Rights Reserved
mod_version=1.2.0
mod_group_id=com.panthrixsgalaxy
mod_authors=Panthrix
mod_credits=Hecho con Forge para Minecraft 1.20.1
mod_url=https://github.com/Elpanthrix180/panthrix-galaxy
mod_issues_url=https://github.com/Elpanthrix180/panthrix-galaxy/issues
mod_description=Exploración espacial y supervivencia: construye cohetes y naves, despega desde la Tierra y viaja a la Luna, Marte, los asteroides y planetas lejanos. Trajes, oxígeno, energía, armas láser, alienígenas y estaciones espaciales.\n\nSpace exploration and survival: build rockets and ships, take off from Earth and travel to the Moon, Mars, the asteroid belt and distant planets.
